FROM apache/airflow:2.6.3-python3.9
USER root
RUN apt-get update && apt-get install -y --no-install-recommends \
    build-essential \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*
USER airflow
COPY ml_model/requirements.txt /requirements.txt
RUN pip install --no-cache-dir --user -r /requirements.txt
